version: '3.8'

networks:
 shared-network:
   driver: bridge

services:
 redis:
   image: "redis:latest"
   container_name: redis
   ports:
     - "6379:6379"
   networks:
     - shared-network
 stomach-service:  
   build:  
     context: .  
     dockerfile: Stomach/Dockerfile
   container_name: stomach-service
   environment:  
     - DOTNET_RUNNING_IN_CONTAINER=true  
   ports:  
     - "5000:5000"  
     - "5001:5001"  
   volumes:  
     - ./Stomach:/app
   working_dir: /app/bin/Debug/net9.0  
   command: ["dotnet", "Stomach.dll"]  
   networks:
     - shared-network
   depends_on:
     rabbitmq:
       condition: service_healthy
   links: 
      - rabbitmq

 small-intestine-service:
   build:
     context: .
     dockerfile: SmallIntestine/Dockerfile
   container_name: small-intestine-service
   environment:
     - DOTNET_RUNNING_IN_CONTAINER=true
   ports:
     - "6000:6000"
     - "6001:6001"
   volumes:
     - ./SmallIntestine:/app
   working_dir: /app/bin/Debug/net9.0
   command: ["dotnet", "SmallIntestine.dll"]
   networks:
     - shared-network
   depends_on:
     rabbitmq:
       condition: service_healthy
   links: 
      - rabbitmq

 left-atrium-service:
   build:
     context: .
     dockerfile: LeftAtrium/Dockerfile
   container_name: left-atrium-service
   environment:
     - DOTNET_RUNNING_IN_CONTAINER=true
   ports:
     - "7000:7000"
     - "7001:7001"
   volumes:
     - ./LeftAtrium:/app
   working_dir: /app/bin/Debug/net9.0
   command: ["dotnet", "LeftAtrium.dll"]
   networks:
     - shared-network
   depends_on:
     rabbitmq:
       condition: service_healthy
   links: 
      - rabbitmq

 lungs-service:
   build:
     context: .
     dockerfile: Lungs/Dockerfile
   container_name: lungs-service
   environment:
     - DOTNET_RUNNING_IN_CONTAINER=true
   ports:
     - "8000:8000"
     - "8001:8001"
   volumes:
     - ./Lungs:/app
   working_dir: /app/bin/Debug/net9.0
   command: ["dotnet", "Lungs.dll"]
   networks:
     - shared-network
   depends_on:
     rabbitmq:
       condition: service_healthy
   links: 
      - rabbitmq

 mouth-service:
   build:
     context: .  
     dockerfile: Mouth/Dockerfile
   container_name: mouth-service
   environment:  
     - DOTNET_RUNNING_IN_CONTAINER=true  
   ports:  
     - "9000:9000"  
     - "9001:9001"  
   volumes:  
     - ./Mouth:/app
   working_dir: /app/bin/Debug/net9.0  
   command: ["dotnet", "Mouth.dll"]  
   networks:
     - shared-network
   depends_on:
     rabbitmq:
       condition: service_healthy
   links: 
      - rabbitmq

 right-atrium-service:
   build:
     context: .  
     dockerfile: RightAtrium/Dockerfile
   container_name: right-atrium-service
   environment:  
     - DOTNET_RUNNING_IN_CONTAINER=true  
   ports:  
     - "10015:10015"  
     - "10016:10016"  
   volumes:  
     - ./RightAtrium:/app
   working_dir: /app/bin/Debug/net9.0  
   command: ["dotnet", "RightAtrium.dll"]  
   networks:
     - shared-network
   depends_on:
     rabbitmq:
       condition: service_healthy
   links: 
      - rabbitmq

 api-service:
   build:
     context: .  
     dockerfile: api/Dockerfile
   container_name: api-service
   environment:  
     - DOTNET_RUNNING_IN_CONTAINER=true  
   ports:  
     - "11000:11000"  
     - "11001:11001"  
   volumes:  
     - ./api:/app
   working_dir: /app/bin/Debug/net9.0  
   command: ["dotnet", "api.dll"]  
   networks:
     - shared-network
   depends_on:
     rabbitmq:
       condition: service_healthy

 rabbitmq:
   image: "rabbitmq:3-management"
   container_name: rabbitmq
   environment:
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
   ports:
     - "5673:5673"
     - "15673:15673"
   networks:
     - shared-network
   healthcheck:
     test: ["CMD", "rabbitmq-diagnostics", "ping"]
     interval: 10s
     timeout: 10s
     retries: 5
